### ISSUE TITLE
Update redis-plugin to Play 2.4

### ISSUE THREAD

**Issue by benjaminsanborn** [typesafehub/play-plugins#145]
It's a bit early; but with RC1 out, what is the timeline for 2.4 support?

**Comment by jroper** [comment]
We can probably release it as is for 2.4 (out of interest,  does it work now with 2.4.0-RC1, or are there any binary compatibility issues?). What we should do though is update it to use the new modules API, and not require global state.

**Comment by kutzi** [comment]
FYI: I'm getting
[error] /home/developers/ckutz/rwd/rwd-webshop/app/controllers/LoginController.java:66: cannot access play.api.cache.CachePlugin
[error]   class file for play.api.cache.CachePlugin not found
[error] play.Play.application().plugin
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] application - 

! @6m41n5aob - Internal server error, for (GET) [/] ->
 
play.sbt.PlayExceptions$CompilationException: Compilation error[cannot access play.api.cache.CachePlugin
  class file for play.api.cache.CachePlugin not found]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.5.jar:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.5.jar:na]
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]

when trying to use the plugin as is with Play 2.4

**Comment by BBartosz** [comment]
Same error here

**Comment by BBartosz** [comment]
I've got the same error with Play 2.4

**Comment by tomlancaster** [comment]
@jroper what is the new modules api, and where can I find it in the play source? We might be able to provide a PR here.

**Comment by jroper** [comment]
https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection#Play-libraries

**Comment by bbatarelo** [comment]
@jroper what is the status of this issue? I have a big production app partly migrated to 2.4, but one of the core features relies on redis plugin. It would be helpful to know timeline so I can plan migration. Thanks.

**Comment by jroper** [comment]
I'm too busy to do any work on this at the moment.  Note the big disclaimer in the readme of this repo:

> These plugins are not supported by Typesafe and no guarantee is made that they will be maintained or upgraded to new versions of Play in a timely manner.
> 
> Use at your own risk.

If you're going to use this in a production app, you should be prepared to maintain it yourself.

**Comment by tomlancaster** [comment]
@jroper I don't think that DI documentation is very helpful, unfortunately. What I should have asked for is the location of the cache interface that is supposed to be followed in a cache plugin. I'm having trouble finding that.

Also, totally fair that there are disclaimers on using this, but also worth noting that, in a sense, TypeSafe *broke this* with changes to interfaces. Since TypeSafe also created this and maintained it, it's understandable that folks would expect TypeSafe to fix it, or at least to work with the community to get it fixed.

**Comment by PR-O** [comment]
Hi guys, we too are in desperate need for a Play 2.4 module update for this plugin. I've been trying to refactor this plugin to a module, but as I'm not very proficient in Scala and new to modules as well as the refactored CacheApi, I'm having some trouble grasping what's the best way to go.

I suppose the new RedisCache module will extend AbstractModule and be loaded once on startup as an eager singleton, correct? This is how I've already created several onStart Singleton modules.

Or should it be added to the CacheManager and injected when needed using the @NamedCached annotation?

Then on the implementation of the module: should this reflect the EhCache implementation? Should we follow the EhCache implementation in play.api.cache.Cache.scala ?

**Comment by tomlancaster** [comment]
@PR-O that's the tack I've been taking (follow the EhCache example), so far without much luck. It seems you need to implement the whole thing rather than rely on the CacheManagerProvider in play.api.cache.Cache

**Comment by jroper** [comment]
@PR-O that sounds right.  If you have any difficulties or questions, don't hesitate to post here, or on the play dev mailing list, I'm happy to help.

@tomlancaster That's correct, Play's `CacheManagerProvider` is specific to Ehcache.

The redis plugin as it currently stands only supports one Redis database.  If you're going to keep it like that, the implementation can be very simple, since the bindings don't have to be so dynamic, you can just do a:

```scala
bind[CacheApi].qualifiedWith(new play.cache.NamedCacheImpl("redis")).to[RedisCacheApi]
```

No need for providers or anything.  However if you want to be able to have multiple redis caches, then that's where things will get a bit more complicated.

**Comment by rmmeans** [comment]
^^ This is the way open source is supposed to work - the community pitching in. Sounds like there are a couple of us working on an update to this module, as I started working on it last week Friday myself. 

one thing that wasn't immediately clear to me is with the bump to Java 8 and sbt 0.13.8 - are things still trying to be cross-targeted for scala versions as well, or is 2.11 now also assumed?

**Comment by jroper** [comment]
Play 2.4 still supports both Scala 2.10 and Scala 2.11.  If there's no good reason to drop 2.10, then I'd say keep cross building against 2.10 (the same logic was used for the decision to support 2.10 in Play 2.4).  Generally, compatibility between 2.10 and 2.11 is very high, so it's not hard to support both.  But if there's a good reason to drop 2.10, then personally, I wouldn't have a problem with that, but I'm not using the redis plugin, maybe there's someone that's using and is also stuck on 2.10, they might have a bit more to say.

**Comment by rmmeans** [comment]
I've taken a pretty deep hit at this, going to need some more feedback though as I renamed some of the package structure etc. See referenced pull req. 

I left the cross compiling, etc in but I did increase the JVM source and target to 1.8 since Play 2.4 requires the same.

**Comment by jroper** [comment]
Released:

```scala
"com.typesafe.play.modules" %% "play-modules-redis" % "2.4.0"
```

**Comment by PR-O** [comment]
Many thanks @rmmeans !! I'm going to take this thing for a test ride this weekend!

**Comment by tomlancaster** [comment]
thanks, @rmmeans ! I'll be checking this out soon. Kinda hoping it can store anorm results (which the RedisPlugin couldn't)

**Comment by johdah** [comment]
How should this new module be used in Java? I am doing like this currently:

Jedis j = play.Play.application().plugin(RedisPlugin.class).jedisPool().getResource();

How should this be done in the new module?

**Comment by rmmeans** [comment]
@tomlancaster if it can now, it had nothing to do with this change. The module can store any object type that is itself serializable as well as primitive types (Long, Int, Boolean), etc.

@johdah Hmm, might need to do another issue for that one. I would need to inject the JedisPool as it's own dependency, right now could get access to the Sedis pool via Java DI like this.. but then you have to use a Scala function inside of Java.. not that intuitive.

```
package controllers;

import org.sedis.Pool;
import play.mvc.Controller;
import play.mvc.Result;

import javax.inject.Inject;

public class JavaController extends Controller {

    @Inject Pool sedisPool;

    public Result index() {
        sedisPool.withJedisClient()
        return ok("Hello")
    }
}
```
