### ISSUE TITLE
Java-2.4: Use Redis module with Jedis

### ISSUE THREAD

**Issue by johdah** [typesafehub/play-plugins#149]
How should this new module be used in Java? I am doing like this currently:

```java
package actors
...
import com.typesafe.plugin.RedisPlugin;
import redis.clients.jedis.Jedis;
...
public class B2BPublisher extends UntypedActor {
	...
	@Trace(dispatcher=true)
	@Override
	public void onReceive(final Object message) throws Exception {
		Jedis j = play.Play.application().plugin(RedisPlugin.class).jedisPool().getResource();
		try {
			j.incr("b2b.connections");
		} finally {
			play.Play.application().plugin(RedisPlugin.class).jedisPool().returnResource(j);
		}
		...
	}
}
```

**Comment by rmmeans** [comment]
I'll see if I can get a hour or so soon to fix this up.

**Comment by johdah** [comment]
I added the code that was added to the README in a model but when I try to use the jedisPool I get att NullPointerException. Do I have to be in a controller to use the example?

**Comment by johdah** [comment]
Ah, the change isn't released yet?

**Comment by rmmeans** [comment]
Yeah, it hasn't been released yet. I also put in a pull for #154, waiting for that to be accepted and then I'm   typesafe will release 2.4.1 of the plugin.
