### ISSUE TITLE
Redis Plugin - play-modules-redis 2.4.0 can't work in Play 2.4.1

### ISSUE THREAD

**Issue by sunnykaka** [typesafehub/play-plugins#155]
Reports play.api.cache.CachePlugin ClassNotFoundException.

It seems that CachePlugin was removed in Play 2.4.1 and Redis Plugin didn't update.

**Comment by johdah** [comment]
Are you sure it isn't you that is using CachePlugin. I think CachePlugin was removed before 2.4.0 was released.

**Comment by sunnykaka** [comment]
@johdah  

I didn't use CachePlugin. But I found this in play-modules-redis_2.11:2.4.0  

```
class RedisPlugin(app : play.api.Application) extends play.api.cache.CachePlugin {
```

**Comment by jroper** [comment]
@sunnykaka I don't think you did. Searching for the word `CachePlugin` in the redis GitHub repo returns zero results:

https://github.com/typesafehub/play-plugins/search?q=CachePlugin&type=Code&utf8=%E2%9C%93

You must have an older version of the `RedisPlugin` on your classpath, so I'm closing this issue.  If you can find the line of code you paste above anywhere in the `redis-2.4.0` tag of this repository:

https://github.com/typesafehub/play-plugins/tree/redis-2.4.0

Then I'll be happy to reopen.

**Comment by sunnykaka** [comment]
Hi @jroper  

You are right, ```CachePlugin``` was totally removed in the source code in github.  

But it's still in the jar which was deployed to Maven Center Repository.  

I downloaded a jar from http://search.maven.org/remotecontent?filepath=com/typesafe/play/modules/play-modules-redis_2.11/2.4.0/play-modules-redis_2.11-2.4.0.jar  

I found ```CachePlugin``` still in the jar.  
![image](https://cloud.githubusercontent.com/assets/1176838/8493338/561061b8-218b-11e5-96c7-7b169e7e6d5d.png)

I think it's why the error occurred.
Maybe it's a deploy issue?

**Comment by jroper** [comment]
You're right, it is there, it's because I didn't do a clean build when I released it (usually the Scala incremental compiler takes care of issues like this, but not this time). We're going to release 2.4.1 soon, so that will fix the problem.  In the meantime, the existence of that file shouldn't impact anything - if it is, it's because you have it referenced in a `play.plugins` file, which is no longer the way to use the redis plugin.

**Comment by jroper** [comment]
2.4.1 is released.

**Comment by sunnykaka** [comment]
It works like a charm! Thanks.
