### ISSUE TITLE
not found: value use

### ISSUE THREAD

**Issue by graingert** [typesafehub/play-plugins#165]
It seems "use" is undefined in the scala Play 2.3 example

```
Error:(18, 16) not found: value use
    val pool = use[RedisPlugin].sedisPool
               ^
```

**Comment by gmethvin** [comment]
"use" is from the play-plugins package:
https://github.com/typesafehub/play-plugins/blob/master/util/src/main/scala/com/typesafe/plugin/package.scala

As you can see it's essentially the same as play.plugin[RedisPlugin].get,
except with a more useful exception thrown if the plugin doesn't exist.

On Mon, Feb 29, 2016 at 6:04 PM, Thomas Grainger <notifications@github.com>
wrote:

> It seems "use" is undefined in the scala Play 2.3 example
>
> Error:(18, 16) not found: value use
>     val pool = use[RedisPlugin].sedisPool
>                ^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typesafehub/play-plugins/issues/165>.
>



-- 
*Greg Methvin*
*Senior Software Engineer*
Lightbend, Inc. <https://www.lightbend.com/>
